%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%          Generated by MATLAB 9.11 and Fixed-Point Designer 7.3           %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function output = gol_mat_stream_wrapper_fixpt(x,width,kernel)
    fm = get_fimath();
    x_in = fi( x, 0, 8, 0, fm );
    width_in = fi( width, 0, 10, 0, fm );
    kernel_in = fi( kernel, 1, 2, 0, fm );
    [output_out] = gol_mat_stream_fixpt( x_in, width_in, kernel_in );
    output = double( output_out );
end

function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'MaxProductWordLength', 128,...
	     'SumMode','FullPrecision',...
	     'MaxSumWordLength', 128);
end
