-- -------------------------------------------------------------
-- 
-- File Name: E:\Downloads\2021b-10mayFINAL\2021b-10mayFINAL\srcFiles\request_buffer\hdlsrc\request_buffer_test\untimed_ctrl.vhd
-- Created: 2022-05-13 16:42:37
-- 
-- Generated by MATLAB 9.11 and HDL Coder 3.19
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: untimed_ctrl
-- Source Path: request_buffer_test/request_buffer/untimed_ctrl
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY untimed_ctrl IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        valid                             :   IN    std_logic;
        ts                                :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        ls                                :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        UT                                :   IN    std_logic;
        ts_out                            :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        ss                                :   OUT   std_logic_vector(31 DOWNTO 0)  -- uint32
        );
END untimed_ctrl;


ARCHITECTURE rtl OF untimed_ctrl IS

  -- Signals
  SIGNAL ts_unsigned                      : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL ls_unsigned                      : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Add2_out1                        : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL NOT_out1                         : std_logic;
  SIGNAL Delay_out1                       : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Add1_out1                        : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Switch2_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL GreaterThan_relop1               : std_logic;
  SIGNAL AND_out1                         : std_logic;
  SIGNAL AND1_out1                        : std_logic;
  SIGNAL Switch1_out1                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Switch_out1                      : unsigned(31 DOWNTO 0);  -- uint32

BEGIN
  ts_unsigned <= unsigned(ts);

  ls_unsigned <= unsigned(ls);

  Add2_out1 <= ts_unsigned + ls_unsigned;

  NOT_out1 <=  NOT UT;

  Add1_out1 <= Delay_out1 + ls_unsigned;

  
  Switch2_out1 <= Add2_out1 WHEN UT = '0' ELSE
      Add1_out1;

  
  GreaterThan_relop1 <= '1' WHEN Delay_out1 < Add2_out1 ELSE
      '0';

  AND_out1 <=  NOT (valid AND GreaterThan_relop1);

  AND1_out1 <= AND_out1 AND NOT_out1;

  
  Switch1_out1 <= Switch2_out1 WHEN AND1_out1 = '0' ELSE
      Delay_out1;

  Delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay_out1 <= Switch1_out1;
      END IF;
    END IF;
  END PROCESS Delay_process;


  
  Switch_out1 <= ts_unsigned WHEN UT = '0' ELSE
      Delay_out1;

  ts_out <= std_logic_vector(Switch_out1);

  ss <= std_logic_vector(Switch2_out1);

END rtl;

