-- -------------------------------------------------------------
-- 
-- File Name: E:\Downloads\2021b-10mayFINAL\2021b-10mayFINAL\srcFiles\filter_block\hdlsrc\filter_block_test\Subsystem_Reference.vhd
-- Created: 2022-05-12 15:03:01
-- 
-- Generated by MATLAB 9.11 and HDL Coder 3.19
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 1
-- Target subsystem base rate: 1
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        1
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- stream_out                    ce_out        1
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Subsystem_Reference
-- Source Path: filter_block_test/Subsystem Reference
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.Subsystem_Reference_pkg.ALL;

ENTITY Subsystem_Reference IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        coeffs                            :   IN    vector_of_std_logic_vector8(0 TO 9);  -- uint8 [10]
        stream_in                         :   IN    vector_of_std_logic_vector4(0 TO 7);  -- sfix4_E2 [8]
        ce_out                            :   OUT   std_logic;
        stream_out                        :   OUT   vector_of_std_logic_vector32(0 TO 7)  -- sfix32_E2 [8]
        );
END Subsystem_Reference;


ARCHITECTURE rtl OF Subsystem_Reference IS

  -- Component Declarations
  COMPONENT filters
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          stream_in                       :   IN    vector_of_std_logic_vector4(0 TO 7);  -- sfix4_E2 [8]
          coeffs                          :   IN    vector_of_std_logic_vector8(0 TO 9);  -- uint8 [10]
          stream_out                      :   OUT   vector_of_std_logic_vector32(0 TO 7)  -- sfix32_E2 [8]
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : filters
    USE ENTITY work.filters(rtl);

  -- Signals
  SIGNAL filters_out1                     : vector_of_std_logic_vector32(0 TO 7);  -- ufix32 [8]

BEGIN
  u_filters_instance1 : filters
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              stream_in => stream_in,  -- sfix4_E2 [8]
              coeffs => coeffs,  -- uint8 [10]
              stream_out => filters_out1  -- sfix32_E2 [8]
              );

  ce_out <= clk_enable;

  stream_out <= filters_out1;

END rtl;

