-- -------------------------------------------------------------
-- 

-- File Name: E:\Downloads\2021b-10mayFINAL\2021b-10mayFINAL\srcFiles\coeff_bank\hdlsrc\coeff_bank_integration_test\fi_splitter_block6.vhd
-- Created: 2022-05-13 10:10:53
-- 
-- Generated by MATLAB 9.11 and HDL Coder 3.19
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: fi_splitter_block6
-- Source Path: coeff_bank_integration_test/coeff_bank/ul_filter_bank/multiple_rams/fi_splitter
-- Hierarchy Level: 3
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.coeff_bank_pac.ALL;

ENTITY fi_splitter_block6 IS
  PORT( in_word                           :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        out_arr                           :   OUT   vector_of_std_logic_vector8(0 TO 1)  -- uint8 [2]
        );
END fi_splitter_block6;


ARCHITECTURE rtl OF fi_splitter_block6 IS

  -- Component Declarations
  COMPONENT fi_splitter_block2
    PORT( in_data                         :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          out_rsvd                        :   OUT   vector_of_std_logic_vector8(0 TO 1)  -- uint8 [2]
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : fi_splitter_block2
    USE ENTITY work.fi_splitter_block2(rtl);

  -- Signals
  SIGNAL fi_splitter_out1                 : vector_of_std_logic_vector8(0 TO 1);  -- ufix8 [2]

BEGIN
  Ufi_splitter_7 : fi_splitter_block2
    PORT MAP( in_data => in_word,  -- uint16
              out_rsvd => fi_splitter_out1  -- uint8 [2]
              );

  out_arr <= fi_splitter_out1;

END rtl;

