function out = req_base(id, fn, UC, UT, SEND, filter_address, dist_address, ts, ls)
    load("constants.mat", "id_bitwidth", "ts_bitwidth", "ls_bitwidth", "bank_bitwidth", "fn_bitwidth")
    if(islogical(id) && ~id)
        out = struct( ...
            'type', 'req_base',...
            'id', fi(0, false, id_bitwidth, 0), ...
            'fn', fi(0, false, fn_bitwidth, 0), ...
            'UC', false, ...
            'UT', false, ...
            'SEND', false, ...
            'filter_address', fi(0, false, bank_bitwidth, 0), ...
            'dist_address', fi(0, false, bank_bitwidth, 0), ...
            'ts', fi(0, false, ts_bitwidth, 0), ...
            'ls', fi(0, false, ls_bitwidth, 0), ...
            'valid', false);
    else
        out = struct( ...
            'type', 'req_base',...
            'id', fi(id, false, id_bitwidth, 0), ...
            'fn', fi(fn, false, fn_bitwidth, 0), ...
            'UC', logical(UC), ...
            'UT', logical(UT), ...
            'SEND', logical(SEND), ...
            'filter_address', fi(filter_address, false, bank_bitwidth, 0), ...
            'dist_address', fi(dist_address, false, bank_bitwidth, 0), ...
            'ts', fi(ts, false, ts_bitwidth, 0), ...
            'ls', fi(ls, false, ls_bitwidth, 0), ...
            'valid', true);
    end
end

