-- -------------------------------------------------------------
-- 
-- File Name: E:\Downloads\2021b-10mayFINAL\2021b-10mayFINAL\srcFiles\combiner\hdlsrc\DIG_IF_test\combiner.vhd
-- Created: 2022-05-26 16:33:24
-- 
-- Generated by MATLAB 9.11 and HDL Coder 3.19
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: combiner
-- Source Path: DIG_IF_test/DIG_IF/combining/combiner
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.combining_pac.ALL;

ENTITY combiner IS
  PORT( data_streams_re                   :   IN    vector_of_std_logic_vector20(0 TO 7);  -- ufix20 [8]
        data_streams_im                   :   IN    vector_of_std_logic_vector20(0 TO 7);  -- ufix20 [8]
        coeffs_re                         :   IN    vector_of_std_logic_vector8(0 TO 31);  -- uint8 [32]
        coeffs_im                         :   IN    vector_of_std_logic_vector8(0 TO 31);  -- uint8 [32]
        out_data_re                       :   OUT   vector_of_std_logic_vector28(0 TO 3);  -- ufix28 [4]
        out_data_im                       :   OUT   vector_of_std_logic_vector28(0 TO 3)  -- ufix28 [4]
        );
END combiner;


ARCHITECTURE rtl OF combiner IS

  -- Signals
  SIGNAL selector_out_re                  : vector_of_std_logic_vector8(0 TO 31);  -- ufix8 [32]
  SIGNAL selector_out_re_1                : vector_of_unsigned8(0 TO 31);  -- uint8 [32]
  SIGNAL selector_out_im                  : vector_of_unsigned8(0 TO 31);  -- uint8 [32]
  SIGNAL alpha_re                         : vector_of_unsigned8(0 TO 31);  -- uint8 [32]
  SIGNAL alpha_im                         : vector_of_unsigned8(0 TO 31);  -- uint8 [32]
  SIGNAL selector_out_re_2                : vector_of_std_logic_vector20(0 TO 31);  -- ufix20 [32]
  SIGNAL selector_out_re_3                : vector_of_unsigned20(0 TO 31);  -- ufix20 [32]
  SIGNAL selector_out_im_1                : vector_of_unsigned20(0 TO 31);  -- ufix20 [32]
  SIGNAL alpha_re_1                       : vector_of_unsigned20(0 TO 31);  -- ufix20 [32]
  SIGNAL alpha_im_1                       : vector_of_unsigned20(0 TO 31);  -- ufix20 [32]
  SIGNAL MMul_dot_product_Re_AC           : vector_of_unsigned28(0 TO 31);  -- ufix28 [32]
  SIGNAL selector_out_im_2                : vector_of_std_logic_vector8(0 TO 31);  -- ufix8 [32]
  SIGNAL selector_out_im_3                : vector_of_std_logic_vector20(0 TO 31);  -- ufix20 [32]
  SIGNAL mulOutput                        : vector_of_unsigned28(0 TO 31);  -- ufix28 [32]
  SIGNAL mulOutput_1                      : vector_of_unsigned29(0 TO 31);  -- ufix29 [32]
  SIGNAL mulOutput_2                      : vector_of_unsigned28(0 TO 31);  -- ufix28 [32]
  SIGNAL reshape_out_re                   : matrix_of_unsigned28(0 TO 7, 0 TO 3);  -- ufix28 [8x4]
  SIGNAL reshape_out_im                   : matrix_of_unsigned28(0 TO 7, 0 TO 3);  -- ufix28 [8x4]
  SIGNAL MMul_dot_product1_mul_temp       : vector_of_unsigned28(0 TO 31);  -- ufix28 [32]
  SIGNAL MMul_dot_product_Im_AD           : vector_of_signed29(0 TO 31);  -- sfix29 [32]
  SIGNAL mulOutput_3                      : vector_of_unsigned28(0 TO 31);  -- ufix28 [32]
  SIGNAL MultiplyAdd1_add_add_cast        : vector_of_signed31(0 TO 31);  -- sfix31 [32]
  SIGNAL mulOutput_4                      : vector_of_signed31(0 TO 31);  -- sfix31 [32]
  SIGNAL mulOutput_5                      : vector_of_unsigned28(0 TO 31);  -- ufix28 [32]
  SIGNAL selector_out_re_4                : vector_of_unsigned28(0 TO 3);  -- ufix28 [4]
  SIGNAL selector_out_im_4                : vector_of_unsigned28(0 TO 3);  -- ufix28 [4]
  SIGNAL selector_out_re_5                : vector_of_unsigned28(0 TO 3);  -- ufix28 [4]
  SIGNAL selector_out_im_5                : vector_of_unsigned28(0 TO 3);  -- ufix28 [4]
  SIGNAL MMul_add_01_out_re               : vector_of_unsigned28(0 TO 3);  -- ufix28 [4]
  SIGNAL MMul_add_01_out_im               : vector_of_unsigned28(0 TO 3);  -- ufix28 [4]
  SIGNAL selector_out_re_6                : vector_of_unsigned28(0 TO 3);  -- ufix28 [4]
  SIGNAL selector_out_im_6                : vector_of_unsigned28(0 TO 3);  -- ufix28 [4]
  SIGNAL MMul_add_12_out_re               : vector_of_unsigned28(0 TO 3);  -- ufix28 [4]
  SIGNAL MMul_add_12_out_im               : vector_of_unsigned28(0 TO 3);  -- ufix28 [4]
  SIGNAL selector_out_re_7                : vector_of_unsigned28(0 TO 3);  -- ufix28 [4]
  SIGNAL selector_out_im_7                : vector_of_unsigned28(0 TO 3);  -- ufix28 [4]
  SIGNAL MMul_add_23_out_re               : vector_of_unsigned28(0 TO 3);  -- ufix28 [4]
  SIGNAL MMul_add_23_out_im               : vector_of_unsigned28(0 TO 3);  -- ufix28 [4]
  SIGNAL selector_out_re_8                : vector_of_unsigned28(0 TO 3);  -- ufix28 [4]
  SIGNAL selector_out_im_8                : vector_of_unsigned28(0 TO 3);  -- ufix28 [4]
  SIGNAL MMul_add_34_out_re               : vector_of_unsigned28(0 TO 3);  -- ufix28 [4]
  SIGNAL MMul_add_34_out_im               : vector_of_unsigned28(0 TO 3);  -- ufix28 [4]
  SIGNAL selector_out_re_9                : vector_of_unsigned28(0 TO 3);  -- ufix28 [4]
  SIGNAL selector_out_im_9                : vector_of_unsigned28(0 TO 3);  -- ufix28 [4]
  SIGNAL MMul_add_45_out_re               : vector_of_unsigned28(0 TO 3);  -- ufix28 [4]
  SIGNAL MMul_add_45_out_im               : vector_of_unsigned28(0 TO 3);  -- ufix28 [4]
  SIGNAL selector_out_re_10               : vector_of_unsigned28(0 TO 3);  -- ufix28 [4]
  SIGNAL selector_out_im_10               : vector_of_unsigned28(0 TO 3);  -- ufix28 [4]
  SIGNAL MMul_add_56_out_re               : vector_of_unsigned28(0 TO 3);  -- ufix28 [4]
  SIGNAL MMul_add_56_out_im               : vector_of_unsigned28(0 TO 3);  -- ufix28 [4]
  SIGNAL selector_out_re_11               : vector_of_unsigned28(0 TO 3);  -- ufix28 [4]
  SIGNAL selector_out_im_11               : vector_of_unsigned28(0 TO 3);  -- ufix28 [4]
  SIGNAL alpha_re_2                       : vector_of_unsigned28(0 TO 3);  -- ufix28 [4]
  SIGNAL alpha_im_2                       : vector_of_unsigned28(0 TO 3);  -- ufix28 [4]
  SIGNAL MatrixMultiply_out1_re           : vector_of_unsigned28(0 TO 3);  -- ufix28 [4]
  SIGNAL MatrixMultiply_out1_im           : vector_of_unsigned28(0 TO 3);  -- ufix28 [4]

BEGIN
  selector_out_re(0) <= coeffs_re(0);
  selector_out_re(1) <= coeffs_re(4);
  selector_out_re(2) <= coeffs_re(8);
  selector_out_re(3) <= coeffs_re(12);
  selector_out_re(4) <= coeffs_re(16);
  selector_out_re(5) <= coeffs_re(20);
  selector_out_re(6) <= coeffs_re(24);
  selector_out_re(7) <= coeffs_re(28);
  selector_out_re(8) <= coeffs_re(1);
  selector_out_re(9) <= coeffs_re(5);
  selector_out_re(10) <= coeffs_re(9);
  selector_out_re(11) <= coeffs_re(13);
  selector_out_re(12) <= coeffs_re(17);
  selector_out_re(13) <= coeffs_re(21);
  selector_out_re(14) <= coeffs_re(25);
  selector_out_re(15) <= coeffs_re(29);
  selector_out_re(16) <= coeffs_re(2);
  selector_out_re(17) <= coeffs_re(6);
  selector_out_re(18) <= coeffs_re(10);
  selector_out_re(19) <= coeffs_re(14);
  selector_out_re(20) <= coeffs_re(18);
  selector_out_re(21) <= coeffs_re(22);
  selector_out_re(22) <= coeffs_re(26);
  selector_out_re(23) <= coeffs_re(30);
  selector_out_re(24) <= coeffs_re(3);
  selector_out_re(25) <= coeffs_re(7);
  selector_out_re(26) <= coeffs_re(11);
  selector_out_re(27) <= coeffs_re(15);
  selector_out_re(28) <= coeffs_re(19);
  selector_out_re(29) <= coeffs_re(23);
  selector_out_re(30) <= coeffs_re(27);
  selector_out_re(31) <= coeffs_re(31);

  outputgen5: FOR kk IN 0 TO 31 GENERATE
    selector_out_re_1(kk) <= unsigned(selector_out_re(kk));
  END GENERATE;

  alpha_reGEN_LABEL: FOR d0 IN 0 TO 31 GENERATE
    alpha_re(d0) <= selector_out_re_1(d0);
  END GENERATE;

  selector_out_re_2(0) <= data_streams_re(0);
  selector_out_re_2(1) <= data_streams_re(1);
  selector_out_re_2(2) <= data_streams_re(2);
  selector_out_re_2(3) <= data_streams_re(3);
  selector_out_re_2(4) <= data_streams_re(4);
  selector_out_re_2(5) <= data_streams_re(5);
  selector_out_re_2(6) <= data_streams_re(6);
  selector_out_re_2(7) <= data_streams_re(7);
  selector_out_re_2(8) <= data_streams_re(0);
  selector_out_re_2(9) <= data_streams_re(1);
  selector_out_re_2(10) <= data_streams_re(2);
  selector_out_re_2(11) <= data_streams_re(3);
  selector_out_re_2(12) <= data_streams_re(4);
  selector_out_re_2(13) <= data_streams_re(5);
  selector_out_re_2(14) <= data_streams_re(6);
  selector_out_re_2(15) <= data_streams_re(7);
  selector_out_re_2(16) <= data_streams_re(0);
  selector_out_re_2(17) <= data_streams_re(1);
  selector_out_re_2(18) <= data_streams_re(2);
  selector_out_re_2(19) <= data_streams_re(3);
  selector_out_re_2(20) <= data_streams_re(4);
  selector_out_re_2(21) <= data_streams_re(5);
  selector_out_re_2(22) <= data_streams_re(6);
  selector_out_re_2(23) <= data_streams_re(7);
  selector_out_re_2(24) <= data_streams_re(0);
  selector_out_re_2(25) <= data_streams_re(1);
  selector_out_re_2(26) <= data_streams_re(2);
  selector_out_re_2(27) <= data_streams_re(3);
  selector_out_re_2(28) <= data_streams_re(4);
  selector_out_re_2(29) <= data_streams_re(5);
  selector_out_re_2(30) <= data_streams_re(6);
  selector_out_re_2(31) <= data_streams_re(7);

  outputgen4: FOR kk IN 0 TO 31 GENERATE
    selector_out_re_3(kk) <= unsigned(selector_out_re_2(kk));
  END GENERATE;

  alpha_re_1GEN_LABEL: FOR d0 IN 0 TO 31 GENERATE
    alpha_re_1(d0) <= selector_out_re_3(d0);
  END GENERATE;


  MMul_dot_product_Re_AC_gen: FOR t_0 IN 0 TO 31 GENERATE
    MMul_dot_product_Re_AC(t_0) <= alpha_re(t_0) * alpha_re_1(t_0);
  END GENERATE MMul_dot_product_Re_AC_gen;


  selector_out_im_2(0) <= coeffs_im(0);
  selector_out_im_2(1) <= coeffs_im(4);
  selector_out_im_2(2) <= coeffs_im(8);
  selector_out_im_2(3) <= coeffs_im(12);
  selector_out_im_2(4) <= coeffs_im(16);
  selector_out_im_2(5) <= coeffs_im(20);
  selector_out_im_2(6) <= coeffs_im(24);
  selector_out_im_2(7) <= coeffs_im(28);
  selector_out_im_2(8) <= coeffs_im(1);
  selector_out_im_2(9) <= coeffs_im(5);
  selector_out_im_2(10) <= coeffs_im(9);
  selector_out_im_2(11) <= coeffs_im(13);
  selector_out_im_2(12) <= coeffs_im(17);
  selector_out_im_2(13) <= coeffs_im(21);
  selector_out_im_2(14) <= coeffs_im(25);
  selector_out_im_2(15) <= coeffs_im(29);
  selector_out_im_2(16) <= coeffs_im(2);
  selector_out_im_2(17) <= coeffs_im(6);
  selector_out_im_2(18) <= coeffs_im(10);
  selector_out_im_2(19) <= coeffs_im(14);
  selector_out_im_2(20) <= coeffs_im(18);
  selector_out_im_2(21) <= coeffs_im(22);
  selector_out_im_2(22) <= coeffs_im(26);
  selector_out_im_2(23) <= coeffs_im(30);
  selector_out_im_2(24) <= coeffs_im(3);
  selector_out_im_2(25) <= coeffs_im(7);
  selector_out_im_2(26) <= coeffs_im(11);
  selector_out_im_2(27) <= coeffs_im(15);
  selector_out_im_2(28) <= coeffs_im(19);
  selector_out_im_2(29) <= coeffs_im(23);
  selector_out_im_2(30) <= coeffs_im(27);
  selector_out_im_2(31) <= coeffs_im(31);

  outputgen3: FOR kk IN 0 TO 31 GENERATE
    selector_out_im(kk) <= unsigned(selector_out_im_2(kk));
  END GENERATE;

  alpha_imGEN_LABEL: FOR d0 IN 0 TO 31 GENERATE
    alpha_im(d0) <= selector_out_im(d0);
  END GENERATE;

  selector_out_im_3(0) <= data_streams_im(0);
  selector_out_im_3(1) <= data_streams_im(1);
  selector_out_im_3(2) <= data_streams_im(2);
  selector_out_im_3(3) <= data_streams_im(3);
  selector_out_im_3(4) <= data_streams_im(4);
  selector_out_im_3(5) <= data_streams_im(5);
  selector_out_im_3(6) <= data_streams_im(6);
  selector_out_im_3(7) <= data_streams_im(7);
  selector_out_im_3(8) <= data_streams_im(0);
  selector_out_im_3(9) <= data_streams_im(1);
  selector_out_im_3(10) <= data_streams_im(2);
  selector_out_im_3(11) <= data_streams_im(3);
  selector_out_im_3(12) <= data_streams_im(4);
  selector_out_im_3(13) <= data_streams_im(5);
  selector_out_im_3(14) <= data_streams_im(6);
  selector_out_im_3(15) <= data_streams_im(7);
  selector_out_im_3(16) <= data_streams_im(0);
  selector_out_im_3(17) <= data_streams_im(1);
  selector_out_im_3(18) <= data_streams_im(2);
  selector_out_im_3(19) <= data_streams_im(3);
  selector_out_im_3(20) <= data_streams_im(4);
  selector_out_im_3(21) <= data_streams_im(5);
  selector_out_im_3(22) <= data_streams_im(6);
  selector_out_im_3(23) <= data_streams_im(7);
  selector_out_im_3(24) <= data_streams_im(0);
  selector_out_im_3(25) <= data_streams_im(1);
  selector_out_im_3(26) <= data_streams_im(2);
  selector_out_im_3(27) <= data_streams_im(3);
  selector_out_im_3(28) <= data_streams_im(4);
  selector_out_im_3(29) <= data_streams_im(5);
  selector_out_im_3(30) <= data_streams_im(6);
  selector_out_im_3(31) <= data_streams_im(7);

  outputgen2: FOR kk IN 0 TO 31 GENERATE
    selector_out_im_1(kk) <= unsigned(selector_out_im_3(kk));
  END GENERATE;

  alpha_im_1GEN_LABEL: FOR d0 IN 0 TO 31 GENERATE
    alpha_im_1(d0) <= selector_out_im_1(d0);
  END GENERATE;


  mulOutput_gen: FOR t_01 IN 0 TO 31 GENERATE
    mulOutput(t_01) <= alpha_im(t_01) * alpha_im_1(t_01);
  END GENERATE mulOutput_gen;



  mulOutput_1_gen: FOR t_02 IN 0 TO 31 GENERATE
    mulOutput_1(t_02) <= resize(MMul_dot_product_Re_AC(t_02), 29) - resize(mulOutput(t_02), 29);
  END GENERATE mulOutput_1_gen;



  mulOutput_2_gen: FOR ii IN 0 TO 31 GENERATE
    mulOutput_2(ii) <= mulOutput_1(ii)(27 DOWNTO 0);
  END GENERATE mulOutput_2_gen;


  reshape_out_reGEN_LABEL1: FOR d1 IN 0 TO 3 GENERATE
    reshape_out_reGEN_LABEL: FOR d0 IN 0 TO 7 GENERATE
      reshape_out_re(d0, d1) <= mulOutput_2(d0 + (d1 * 8));
    END GENERATE;
  END GENERATE;


  MMul_dot_product_Im_AD_gen: FOR t_03 IN 0 TO 31 GENERATE
    MMul_dot_product1_mul_temp(t_03) <= alpha_re(t_03) * alpha_im_1(t_03);
    MMul_dot_product_Im_AD(t_03) <= signed(resize(MMul_dot_product1_mul_temp(t_03), 29));
  END GENERATE MMul_dot_product_Im_AD_gen;



  mulOutput_3_gen: FOR t_04 IN 0 TO 31 GENERATE
    mulOutput_3(t_04) <= alpha_im(t_04) * alpha_re_1(t_04);
  END GENERATE mulOutput_3_gen;



  mulOutput_4_gen: FOR t_05 IN 0 TO 31 GENERATE
    MultiplyAdd1_add_add_cast(t_05) <= signed(resize(mulOutput_3(t_05), 31));
    mulOutput_4(t_05) <= resize(MMul_dot_product_Im_AD(t_05), 31) + MultiplyAdd1_add_add_cast(t_05);
  END GENERATE mulOutput_4_gen;



  mulOutput_5_gen: FOR ii1 IN 0 TO 31 GENERATE
    mulOutput_5(ii1) <= unsigned(mulOutput_4(ii1)(27 DOWNTO 0));
  END GENERATE mulOutput_5_gen;


  reshape_out_imGEN_LABEL1: FOR d1 IN 0 TO 3 GENERATE
    reshape_out_imGEN_LABEL: FOR d0 IN 0 TO 7 GENERATE
      reshape_out_im(d0, d1) <= mulOutput_5(d0 + (d1 * 8));
    END GENERATE;
  END GENERATE;

  select_0_output : PROCESS (reshape_out_im, reshape_out_re)
  BEGIN

    FOR t_06 IN 0 TO 3 LOOP
      selector_out_re_4(t_06) <= reshape_out_re(0, t_06);
      selector_out_im_4(t_06) <= reshape_out_im(0, t_06);
    END LOOP;

  END PROCESS select_0_output;


  select_1_output : PROCESS (reshape_out_im, reshape_out_re)
  BEGIN

    FOR t_07 IN 0 TO 3 LOOP
      selector_out_re_5(t_07) <= reshape_out_re(1, t_07);
      selector_out_im_5(t_07) <= reshape_out_im(1, t_07);
    END LOOP;

  END PROCESS select_1_output;



  MMul_add_01_out_im_gen: FOR t_08 IN 0 TO 3 GENERATE
    MMul_add_01_out_re(t_08) <= selector_out_re_4(t_08) + selector_out_re_5(t_08);
    MMul_add_01_out_im(t_08) <= selector_out_im_4(t_08) + selector_out_im_5(t_08);
  END GENERATE MMul_add_01_out_im_gen;


  select_2_output : PROCESS (reshape_out_im, reshape_out_re)
  BEGIN

    FOR t_09 IN 0 TO 3 LOOP
      selector_out_re_6(t_09) <= reshape_out_re(2, t_09);
      selector_out_im_6(t_09) <= reshape_out_im(2, t_09);
    END LOOP;

  END PROCESS select_2_output;



  MMul_add_12_out_im_gen: FOR t_010 IN 0 TO 3 GENERATE
    MMul_add_12_out_re(t_010) <= MMul_add_01_out_re(t_010) + selector_out_re_6(t_010);
    MMul_add_12_out_im(t_010) <= MMul_add_01_out_im(t_010) + selector_out_im_6(t_010);
  END GENERATE MMul_add_12_out_im_gen;


  select_3_output : PROCESS (reshape_out_im, reshape_out_re)
  BEGIN

    FOR t_011 IN 0 TO 3 LOOP
      selector_out_re_7(t_011) <= reshape_out_re(3, t_011);
      selector_out_im_7(t_011) <= reshape_out_im(3, t_011);
    END LOOP;

  END PROCESS select_3_output;



  MMul_add_23_out_im_gen: FOR t_012 IN 0 TO 3 GENERATE
    MMul_add_23_out_re(t_012) <= MMul_add_12_out_re(t_012) + selector_out_re_7(t_012);
    MMul_add_23_out_im(t_012) <= MMul_add_12_out_im(t_012) + selector_out_im_7(t_012);
  END GENERATE MMul_add_23_out_im_gen;


  select_4_output : PROCESS (reshape_out_im, reshape_out_re)
  BEGIN

    FOR t_013 IN 0 TO 3 LOOP
      selector_out_re_8(t_013) <= reshape_out_re(4, t_013);
      selector_out_im_8(t_013) <= reshape_out_im(4, t_013);
    END LOOP;

  END PROCESS select_4_output;



  MMul_add_34_out_im_gen: FOR t_014 IN 0 TO 3 GENERATE
    MMul_add_34_out_re(t_014) <= MMul_add_23_out_re(t_014) + selector_out_re_8(t_014);
    MMul_add_34_out_im(t_014) <= MMul_add_23_out_im(t_014) + selector_out_im_8(t_014);
  END GENERATE MMul_add_34_out_im_gen;


  select_5_output : PROCESS (reshape_out_im, reshape_out_re)
  BEGIN

    FOR t_015 IN 0 TO 3 LOOP
      selector_out_re_9(t_015) <= reshape_out_re(5, t_015);
      selector_out_im_9(t_015) <= reshape_out_im(5, t_015);
    END LOOP;

  END PROCESS select_5_output;



  MMul_add_45_out_im_gen: FOR t_016 IN 0 TO 3 GENERATE
    MMul_add_45_out_re(t_016) <= MMul_add_34_out_re(t_016) + selector_out_re_9(t_016);
    MMul_add_45_out_im(t_016) <= MMul_add_34_out_im(t_016) + selector_out_im_9(t_016);
  END GENERATE MMul_add_45_out_im_gen;


  select_6_output : PROCESS (reshape_out_im, reshape_out_re)
  BEGIN

    FOR t_017 IN 0 TO 3 LOOP
      selector_out_re_10(t_017) <= reshape_out_re(6, t_017);
      selector_out_im_10(t_017) <= reshape_out_im(6, t_017);
    END LOOP;

  END PROCESS select_6_output;



  MMul_add_56_out_im_gen: FOR t_018 IN 0 TO 3 GENERATE
    MMul_add_56_out_re(t_018) <= MMul_add_45_out_re(t_018) + selector_out_re_10(t_018);
    MMul_add_56_out_im(t_018) <= MMul_add_45_out_im(t_018) + selector_out_im_10(t_018);
  END GENERATE MMul_add_56_out_im_gen;


  select_7_output : PROCESS (reshape_out_im, reshape_out_re)
  BEGIN

    FOR t_019 IN 0 TO 3 LOOP
      selector_out_re_11(t_019) <= reshape_out_re(7, t_019);
      selector_out_im_11(t_019) <= reshape_out_im(7, t_019);
    END LOOP;

  END PROCESS select_7_output;



  alpha_im_2_gen: FOR t_020 IN 0 TO 3 GENERATE
    alpha_re_2(t_020) <= MMul_add_56_out_re(t_020) + selector_out_re_11(t_020);
    alpha_im_2(t_020) <= MMul_add_56_out_im(t_020) + selector_out_im_11(t_020);
  END GENERATE alpha_im_2_gen;


  MatrixMultiply_out1_reGEN_LABEL: FOR d0 IN 0 TO 3 GENERATE
    MatrixMultiply_out1_re(d0) <= alpha_re_2(d0);
  END GENERATE;

  outputgen1: FOR kk IN 0 TO 3 GENERATE
    out_data_re(kk) <= std_logic_vector(MatrixMultiply_out1_re(kk));
  END GENERATE;

  MatrixMultiply_out1_imGEN_LABEL: FOR d0 IN 0 TO 3 GENERATE
    MatrixMultiply_out1_im(d0) <= alpha_im_2(d0);
  END GENERATE;

  outputgen: FOR kk IN 0 TO 3 GENERATE
    out_data_im(kk) <= std_logic_vector(MatrixMultiply_out1_im(kk));
  END GENERATE;

END rtl;

