-- -------------------------------------------------------------
-- 

-- File Name: E:\Downloads\2021b-10mayFINAL\2021b-10mayFINAL\srcFiles\combiner\hdlsrc\DIG_IF_test\combining.vhd
-- Created: 2022-05-26 16:33:24
-- 
-- Generated by MATLAB 9.11 and HDL Coder 3.19
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 1
-- Target subsystem base rate: 1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: combining
-- Source Path: DIG_IF_test/DIG_IF/combining
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.combining_pac.ALL;

ENTITY combining IS
  PORT( coeffs_re                         :   IN    vector_of_std_logic_vector8(0 TO 31);  -- uint8 [32]
        coeffs_im                         :   IN    vector_of_std_logic_vector8(0 TO 31);  -- uint8 [32]
        dl_ctrl_bus_valid                 :   IN    std_logic;
        dl_ctrl_bus_SEND                  :   IN    std_logic;
        dl_ctrl_bus_UC                    :   IN    std_logic;
        dl_ctrl_bus_filter_address        :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        dl_ctrl_bus_dist_address          :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        dl_ctrl_bus_id                    :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        dl_ctrl_bus_fn                    :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        data_re                           :   IN    vector_of_std_logic_vector20(0 TO 7);  -- ufix20 [8]
        data_im                           :   IN    vector_of_std_logic_vector20(0 TO 7);  -- ufix20 [8]
        dl_stream_re                      :   OUT   vector_of_std_logic_vector28(0 TO 3);  -- ufix28 [4]
        dl_stream_im                      :   OUT   vector_of_std_logic_vector28(0 TO 3);  -- ufix28 [4]
        UC_stream_re                      :   OUT   vector_of_std_logic_vector20(0 TO 7);  -- ufix20 [8]
        UC_stream_im                      :   OUT   vector_of_std_logic_vector20(0 TO 7)  -- ufix20 [8]
        );
END combining;


ARCHITECTURE rtl OF combining IS

  -- Component Declarations
  COMPONENT combiner
    PORT( data_streams_re                 :   IN    vector_of_std_logic_vector20(0 TO 7);  -- ufix20 [8]
          data_streams_im                 :   IN    vector_of_std_logic_vector20(0 TO 7);  -- ufix20 [8]
          coeffs_re                       :   IN    vector_of_std_logic_vector8(0 TO 31);  -- uint8 [32]
          coeffs_im                       :   IN    vector_of_std_logic_vector8(0 TO 31);  -- uint8 [32]
          out_data_re                     :   OUT   vector_of_std_logic_vector28(0 TO 3);  -- ufix28 [4]
          out_data_im                     :   OUT   vector_of_std_logic_vector28(0 TO 3)  -- ufix28 [4]
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : combiner
    USE ENTITY work.combiner(rtl);

  -- Signals
  SIGNAL UC                               : std_logic;
  SIGNAL switch_compare_1                 : std_logic;
  SIGNAL combiner_out1_re                 : vector_of_std_logic_vector28(0 TO 3);  -- ufix28 [4]
  SIGNAL combiner_out1_im                 : vector_of_std_logic_vector28(0 TO 3);  -- ufix28 [4]
  SIGNAL combiner_out1_re_unsigned        : vector_of_unsigned28(0 TO 3);  -- ufix28 [4]
  SIGNAL combiner_out1_im_unsigned        : vector_of_unsigned28(0 TO 3);  -- ufix28 [4]
  SIGNAL Constant1_out1_re                : vector_of_unsigned4(0 TO 3);  -- ufix4 [4]
  SIGNAL Constant1_out1_im                : vector_of_unsigned4(0 TO 3);  -- ufix4 [4]
  SIGNAL Constant1_out1_reshape_dtc_re    : vector_of_unsigned28(0 TO 3);  -- ufix28 [4]
  SIGNAL Constant1_out1_reshape_dtc_im    : vector_of_unsigned28(0 TO 3);  -- ufix28 [4]
  SIGNAL Switch1_out1_re                  : vector_of_unsigned28(0 TO 3);  -- ufix28 [4]
  SIGNAL Switch1_out1_im                  : vector_of_unsigned28(0 TO 3);  -- ufix28 [4]
  SIGNAL switch_compare_1_1               : std_logic;
  SIGNAL Constant_out1_re                 : vector_of_unsigned4(0 TO 7);  -- ufix4 [8]
  SIGNAL Constant_out1_im                 : vector_of_unsigned4(0 TO 7);  -- ufix4 [8]
  SIGNAL Constant_out1_reshape_dtc_re     : vector_of_unsigned20(0 TO 7);  -- ufix20 [8]
  SIGNAL Constant_out1_reshape_dtc_im     : vector_of_unsigned20(0 TO 7);  -- ufix20 [8]
  SIGNAL data_re_unsigned                 : vector_of_unsigned20(0 TO 7);  -- ufix20 [8]
  SIGNAL data_im_unsigned                 : vector_of_unsigned20(0 TO 7);  -- ufix20 [8]
  SIGNAL Switch_out1_re                   : vector_of_unsigned20(0 TO 7);  -- ufix20 [8]
  SIGNAL Switch_out1_im                   : vector_of_unsigned20(0 TO 7);  -- ufix20 [8]

BEGIN
  Ucombiner_1 : combiner
    PORT MAP( data_streams_re => data_re,  -- ufix20 [8]
              data_streams_im => data_im,  -- ufix20 [8]
              coeffs_re => coeffs_re,  -- uint8 [32]
              coeffs_im => coeffs_im,  -- uint8 [32]
              out_data_re => combiner_out1_re,  -- ufix28 [4]
              out_data_im => combiner_out1_im  -- ufix28 [4]
              );

  UC <= dl_ctrl_bus_UC;

  
  switch_compare_1 <= '1' WHEN UC > '0' ELSE
      '0';

  outputgen7: FOR kk IN 0 TO 3 GENERATE
    combiner_out1_re_unsigned(kk) <= unsigned(combiner_out1_re(kk));
  END GENERATE;

  outputgen6: FOR kk IN 0 TO 3 GENERATE
    combiner_out1_im_unsigned(kk) <= unsigned(combiner_out1_im(kk));
  END GENERATE;

  Constant1_out1_re(0) <= to_unsigned(16#0#, 4);
  Constant1_out1_im(0) <= to_unsigned(16#0#, 4);
  Constant1_out1_re(1) <= to_unsigned(16#0#, 4);
  Constant1_out1_im(1) <= to_unsigned(16#0#, 4);
  Constant1_out1_re(2) <= to_unsigned(16#0#, 4);
  Constant1_out1_im(2) <= to_unsigned(16#0#, 4);
  Constant1_out1_re(3) <= to_unsigned(16#0#, 4);
  Constant1_out1_im(3) <= to_unsigned(16#0#, 4);


  Constant1_out1_reshape_dtc_im_gen: FOR ii IN 0 TO 3 GENERATE
    Constant1_out1_reshape_dtc_re(ii) <= resize(Constant1_out1_re(ii), 28);
    Constant1_out1_reshape_dtc_im(ii) <= resize(Constant1_out1_im(ii), 28);
  END GENERATE Constant1_out1_reshape_dtc_im_gen;


  
  Switch1_out1_re <= combiner_out1_re_unsigned WHEN switch_compare_1 = '0' ELSE
      Constant1_out1_reshape_dtc_re;
  
  Switch1_out1_im <= combiner_out1_im_unsigned WHEN switch_compare_1 = '0' ELSE
      Constant1_out1_reshape_dtc_im;

  outputgen5: FOR kk IN 0 TO 3 GENERATE
    dl_stream_re(kk) <= std_logic_vector(Switch1_out1_re(kk));
  END GENERATE;

  outputgen4: FOR kk IN 0 TO 3 GENERATE
    dl_stream_im(kk) <= std_logic_vector(Switch1_out1_im(kk));
  END GENERATE;

  
  switch_compare_1_1 <= '1' WHEN UC > '0' ELSE
      '0';

  Constant_out1_re(0) <= to_unsigned(16#0#, 4);
  Constant_out1_im(0) <= to_unsigned(16#0#, 4);
  Constant_out1_re(1) <= to_unsigned(16#0#, 4);
  Constant_out1_im(1) <= to_unsigned(16#0#, 4);
  Constant_out1_re(2) <= to_unsigned(16#0#, 4);
  Constant_out1_im(2) <= to_unsigned(16#0#, 4);
  Constant_out1_re(3) <= to_unsigned(16#0#, 4);
  Constant_out1_im(3) <= to_unsigned(16#0#, 4);
  Constant_out1_re(4) <= to_unsigned(16#0#, 4);
  Constant_out1_im(4) <= to_unsigned(16#0#, 4);
  Constant_out1_re(5) <= to_unsigned(16#0#, 4);
  Constant_out1_im(5) <= to_unsigned(16#0#, 4);
  Constant_out1_re(6) <= to_unsigned(16#0#, 4);
  Constant_out1_im(6) <= to_unsigned(16#0#, 4);
  Constant_out1_re(7) <= to_unsigned(16#0#, 4);
  Constant_out1_im(7) <= to_unsigned(16#0#, 4);


  Constant_out1_reshape_dtc_im_gen: FOR ii1 IN 0 TO 7 GENERATE
    Constant_out1_reshape_dtc_re(ii1) <= resize(Constant_out1_re(ii1), 20);
    Constant_out1_reshape_dtc_im(ii1) <= resize(Constant_out1_im(ii1), 20);
  END GENERATE Constant_out1_reshape_dtc_im_gen;


  outputgen3: FOR kk IN 0 TO 7 GENERATE
    data_re_unsigned(kk) <= unsigned(data_re(kk));
  END GENERATE;

  outputgen2: FOR kk IN 0 TO 7 GENERATE
    data_im_unsigned(kk) <= unsigned(data_im(kk));
  END GENERATE;

  
  Switch_out1_re <= Constant_out1_reshape_dtc_re WHEN switch_compare_1_1 = '0' ELSE
      data_re_unsigned;
  
  Switch_out1_im <= Constant_out1_reshape_dtc_im WHEN switch_compare_1_1 = '0' ELSE
      data_im_unsigned;

  outputgen1: FOR kk IN 0 TO 7 GENERATE
    UC_stream_re(kk) <= std_logic_vector(Switch_out1_re(kk));
  END GENERATE;

  outputgen: FOR kk IN 0 TO 7 GENERATE
    UC_stream_im(kk) <= std_logic_vector(Switch_out1_im(kk));
  END GENERATE;

END rtl;

