-- -------------------------------------------------------------
-- 

-- File Name: E:\Downloads\2021b-10mayFINAL\2021b-10mayFINAL\srcFiles\DIG_IF\hdlsrc\DIG_IF_test\combiner_to_complex.vhd
-- Created: 2022-05-10 17:23:04
-- 
-- Generated by MATLAB 9.11 and HDL Coder 3.19
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: combiner_to_complex
-- Source Path: DIG_IF_test/DIG_IF/combiner_to_complex
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.DIG_IF_pac.ALL;

ENTITY combiner_to_complex IS
  PORT( in_stream                         :   IN    vector_of_std_logic_vector8(0 TO 63);  -- uint8 [64]
        out_stream_re                     :   OUT   vector_of_std_logic_vector8(0 TO 31);  -- uint8 [32]
        out_stream_im                     :   OUT   vector_of_std_logic_vector8(0 TO 31)  -- uint8 [32]
        );
END combiner_to_complex;


ARCHITECTURE rtl OF combiner_to_complex IS

  -- Component Declarations
  COMPONENT combine_to_complex
    PORT( In1                             :   IN    vector_of_std_logic_vector8(0 TO 1);  -- uint8 [2]
          Out1_re                         :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
          Out1_im                         :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : combine_to_complex
    USE ENTITY work.combine_to_complex(rtl);

  -- Signals
  SIGNAL combine_to_complex_out1_re       : vector_of_std_logic_vector8(0 TO 31);  -- ufix8 [32]
  SIGNAL combine_to_complex_out1_im       : vector_of_std_logic_vector8(0 TO 31);  -- ufix8 [32]

BEGIN
  GEN_LABEL: FOR kk IN 0 TO 31 GENERATE
    Ucombine_to_complex_1 : combine_to_complex
      PORT MAP( In1 => in_stream(2*kk TO 2*(kk+1) - 1),  -- uint8 [2]
                Out1_re => combine_to_complex_out1_re(kk),  -- uint8
                Out1_im => combine_to_complex_out1_im(kk)  -- uint8
                );
  END GENERATE;

  out_stream_re <= combine_to_complex_out1_re;

  out_stream_im <= combine_to_complex_out1_im;

END rtl;

