-- -------------------------------------------------------------
-- 

-- File Name: E:\Downloads\2021b-10mayFINAL\2021b-10mayFINAL\srcFiles\DIG_IF\hdlsrc\DIG_IF_test\combine_to_complex_block.vhd
-- Created: 2022-05-10 17:23:04
-- 
-- Generated by MATLAB 9.11 and HDL Coder 3.19
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: combine_to_complex_block
-- Source Path: DIG_IF_test/DIG_IF/splitter_to_complex/combine_to_complex
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.DIG_IF_pac.ALL;

ENTITY combine_to_complex_block IS
  PORT( In1                               :   IN    vector_of_std_logic_vector8(0 TO 1);  -- uint8 [2]
        Out1_re                           :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        Out1_im                           :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
        );
END combine_to_complex_block;


ARCHITECTURE rtl OF combine_to_complex_block IS

BEGIN
  Out1_re <= In1(0);

  Out1_im <= In1(1);

END rtl;

