-- -------------------------------------------------------------
-- 
-- File Name: E:\Downloads\2021b-10mayFINAL\2021b-10mayFINAL\srcFiles\DIG_IF\hdlsrc\DIG_IF_test\dl_filter.vhd
-- Created: 2022-05-10 17:23:04
-- 
-- Generated by MATLAB 9.11 and HDL Coder 3.19
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: dl_filter
-- Source Path: DIG_IF_test/DIG_IF/dl_filter
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.DIG_IF_pac.ALL;

ENTITY dl_filter IS
  PORT( clk                               :   IN    std_logic;
        coeffs                            :   IN    vector_of_std_logic_vector8(0 TO 9);  -- uint8 [10]
        stream_in_re                      :   IN    vector_of_std_logic_vector4(0 TO 7);  -- ufix4 [8]
        stream_in_im                      :   IN    vector_of_std_logic_vector4(0 TO 7);  -- ufix4 [8]
        stream_out_re                     :   OUT   vector_of_std_logic_vector20(0 TO 7);  -- ufix20 [8]
        stream_out_im                     :   OUT   vector_of_std_logic_vector20(0 TO 7)  -- ufix20 [8]
        );
END dl_filter;


ARCHITECTURE rtl OF dl_filter IS

  -- Component Declarations
  COMPONENT filters
    PORT( clk                             :   IN    std_logic;
          stream_in_re                    :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
          stream_in_im                    :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
          coeffs                          :   IN    vector_of_std_logic_vector8(0 TO 9);  -- uint8 [10]
          stream_out_re                   :   OUT   std_logic_vector(19 DOWNTO 0);  -- ufix20
          stream_out_im                   :   OUT   std_logic_vector(19 DOWNTO 0)  -- ufix20
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : filters
    USE ENTITY work.filters(rtl);

  -- Signals
  SIGNAL filters_out1_re                  : vector_of_std_logic_vector20(0 TO 7);  -- ufix20 [8]
  SIGNAL filters_out1_im                  : vector_of_std_logic_vector20(0 TO 7);  -- ufix20 [8]

BEGIN
  GEN_LABEL: FOR kk IN 0 TO 7 GENERATE
    Ufilters_1 : filters
      PORT MAP( clk => clk,
                stream_in_re => stream_in_re(kk),  -- ufix4
                stream_in_im => stream_in_im(kk),  -- ufix4
                coeffs => coeffs,  -- uint8 [10]
                stream_out_re => filters_out1_re(kk),  -- ufix20
                stream_out_im => filters_out1_im(kk)  -- ufix20
                );
  END GENERATE;

  stream_out_re <= filters_out1_re;

  stream_out_im <= filters_out1_im;

END rtl;

