-- -------------------------------------------------------------
-- 

-- File Name: E:\Downloads\2021b-10mayFINAL\2021b-10mayFINAL\srcFiles\DIG_IF\hdlsrc\DIG_IF_test\fi_splitter.vhd
-- Created: 2022-05-10 17:23:04
-- 
-- Generated by MATLAB 9.11 and HDL Coder 3.19
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: fi_splitter
-- Source Path: DIG_IF_test/DIG_IF/combiner_bank/multiple_rams/fi_splitter/fi_splitter
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.DIG_IF_pac.ALL;

ENTITY fi_splitter IS
  PORT( in_data                           :   IN    std_logic_vector(63 DOWNTO 0);  -- ufix64
        out_rsvd                          :   OUT   vector_of_std_logic_vector8(0 TO 7)  -- uint8 [8]
        );
END fi_splitter;


ARCHITECTURE rtl OF fi_splitter IS

  -- Signals
  SIGNAL in_data_unsigned                 : unsigned(63 DOWNTO 0);  -- ufix64
  SIGNAL out_tmp                          : vector_of_unsigned8(0 TO 7);  -- uint8 [8]

BEGIN
  in_data_unsigned <= unsigned(in_data);

  fi_splitter_1_output : PROCESS (in_data_unsigned)
    VARIABLE in_data1 : unsigned(63 DOWNTO 0);
  BEGIN
    --MATLAB Function 'DIG_IF/combiner_bank/multiple_rams/fi_splitter/fi_splitter'
    in_data1 := in_data_unsigned;
    out_tmp(7) <= in_data1(7 DOWNTO 0);
    out_tmp(6) <= in_data1(15 DOWNTO 8);
    out_tmp(5) <= in_data1(23 DOWNTO 16);
    out_tmp(4) <= in_data1(31 DOWNTO 24);
    out_tmp(3) <= in_data1(39 DOWNTO 32);
    out_tmp(2) <= in_data1(47 DOWNTO 40);
    out_tmp(1) <= in_data1(55 DOWNTO 48);
    out_tmp(0) <= in_data1(63 DOWNTO 56);
  END PROCESS fi_splitter_1_output;


  outputgen: FOR kk IN 0 TO 7 GENERATE
    out_rsvd(kk) <= std_logic_vector(out_tmp(kk));
  END GENERATE;

END rtl;

