-- -------------------------------------------------------------
-- 
-- File Name: E:\Downloads\2021b-10mayFINAL\2021b-10mayFINAL\srcFiles\DIG_IF\hdlsrc\DIG_IF_test\find_ti.vhd
-- Created: 2022-05-10 17:23:04
-- 
-- Generated by MATLAB 9.11 and HDL Coder 3.19
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: find_ti
-- Source Path: DIG_IF_test/DIG_IF/request_buffer/request_orderer/ts_ctrl/find_ti_index/find_ti
-- Hierarchy Level: 5
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY find_ti IS
  GENERIC( iter                           : integer := 0
           );
  PORT( ts                                :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        ti                                :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        address                           :   OUT   std_logic_vector(5 DOWNTO 0);  -- ufix6
        any                               :   OUT   std_logic
        );
END find_ti;


ARCHITECTURE rtl OF find_ti IS

  -- Signals
  SIGNAL ts_unsigned                      : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL ti_unsigned                      : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Equal_relop1                     : std_logic;
  SIGNAL Constant1_out1                   : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL Switch_out1                      : unsigned(5 DOWNTO 0);  -- ufix6

BEGIN
  ts_unsigned <= unsigned(ts);

  ti_unsigned <= unsigned(ti);

  
  Equal_relop1 <= '1' WHEN ts_unsigned = ti_unsigned ELSE
      '0';

  Constant1_out1 <= to_unsigned(iter, 6);

  
  Switch_out1 <= to_unsigned(16#00#, 6) WHEN Equal_relop1 = '0' ELSE
      Constant1_out1;

  address <= std_logic_vector(Switch_out1);

  any <= Equal_relop1;

END rtl;

