-- -------------------------------------------------------------
-- 
-- File Name: E:\Downloads\2021b-10mayFINAL\2021b-10mayFINAL\srcFiles\DIG_IF\hdlsrc\DIG_IF_test\time_ctrl.vhd
-- Created: 2022-05-10 17:23:04
-- 
-- Generated by MATLAB 9.11 and HDL Coder 3.19
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: time_ctrl
-- Source Path: DIG_IF_test/DIG_IF/time_ctrl
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY time_ctrl IS
  PORT( clk                               :   IN    std_logic;
        reset_x                           :   IN    std_logic;
        in_bus_valid                      :   IN    std_logic;
        in_bus_ti                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        ti                                :   OUT   std_logic_vector(31 DOWNTO 0)  -- uint32
        );
END time_ctrl;


ARCHITECTURE rtl OF time_ctrl IS

  -- Signals
  SIGNAL valid                            : std_logic;
  SIGNAL NOT_out1                         : std_logic;
  SIGNAL ti_1                             : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Switch_out1                      : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Increment_Stored_Integer_out1    : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay_out1                       : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Less_Than_relop1                 : std_logic;
  SIGNAL Switch1_out1                     : unsigned(31 DOWNTO 0);  -- uint32

BEGIN
  valid <= in_bus_valid;

  NOT_out1 <=  NOT valid;

  ti_1 <= unsigned(in_bus_ti);

  Increment_Stored_Integer_out1 <= Switch_out1 + to_unsigned(1, 32);

  Delay_rsvd_process : PROCESS (clk, reset_x)
  BEGIN
    IF reset_x = '1' THEN
      Delay_out1 <= to_unsigned(1, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      Delay_out1 <= Increment_Stored_Integer_out1;
    END IF;
  END PROCESS Delay_rsvd_process;


  
  Less_Than_relop1 <= '1' WHEN Delay_out1 < to_unsigned(4928000, 32) ELSE
      '0';

  
  Switch1_out1 <= to_unsigned(0, 32) WHEN Less_Than_relop1 = '0' ELSE
      Delay_out1;

  
  Switch_out1 <= ti_1 WHEN NOT_out1 = '0' ELSE
      Switch1_out1;

  ti <= std_logic_vector(Switch_out1);

END rtl;

