-- -------------------------------------------------------------
-- 

-- File Name: E:\Downloads\2021b-10mayFINAL\2021b-10mayFINAL\srcFiles\DIG_IF\hdlsrc\DIG_IF_test\transmit_fetching.vhd
-- Created: 2022-05-10 17:23:04
-- 
-- Generated by MATLAB 9.11 and HDL Coder 3.19
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: transmit_fetching
-- Source Path: DIG_IF_test/DIG_IF/transmit_fetching
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY transmit_fetching IS
  PORT( req_in_req_SEND                   :   IN    std_logic;
        req_in_req_fn                     :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        req_in_id                         :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        req_in_valid                      :   IN    std_logic;
        fetch_valid                       :   OUT   std_logic;
        fetch_id                          :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        fetch_fn                          :   OUT   std_logic_vector(15 DOWNTO 0)  -- uint16
        );
END transmit_fetching;


ARCHITECTURE rtl OF transmit_fetching IS

  -- Signals
  SIGNAL valid                            : std_logic;
  SIGNAL SEND                             : std_logic;
  SIGNAL valid_1                          : std_logic;
  SIGNAL id                               : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL fn                               : unsigned(15 DOWNTO 0);  -- uint16

BEGIN
  valid <= req_in_valid;

  SEND <= req_in_req_SEND;

  valid_1 <= valid AND SEND;

  id <= unsigned(req_in_id);

  fetch_id <= std_logic_vector(id);

  fn <= unsigned(req_in_req_fn);

  fetch_fn <= std_logic_vector(fn);

  fetch_valid <= valid_1;

END rtl;

