-- -------------------------------------------------------------
-- 

-- File Name: E:\Downloads\2021b-10mayFINAL\2021b-10mayFINAL\srcFiles\combiner\hdlsrc\DIG_IF_test\combining_pac.vhd
-- Created: 2022-05-26 16:33:24
-- 
-- Generated by MATLAB 9.11 and HDL Coder 3.19
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE combining_pac IS
  TYPE vector_of_std_logic_vector20 IS ARRAY (NATURAL RANGE <>) OF std_logic_vector(19 DOWNTO 0);
  TYPE vector_of_std_logic_vector8 IS ARRAY (NATURAL RANGE <>) OF std_logic_vector(7 DOWNTO 0);
  TYPE vector_of_std_logic_vector28 IS ARRAY (NATURAL RANGE <>) OF std_logic_vector(27 DOWNTO 0);
  TYPE vector_of_unsigned8 IS ARRAY (NATURAL RANGE <>) OF unsigned(7 DOWNTO 0);
  TYPE vector_of_unsigned20 IS ARRAY (NATURAL RANGE <>) OF unsigned(19 DOWNTO 0);
  TYPE vector_of_unsigned28 IS ARRAY (NATURAL RANGE <>) OF unsigned(27 DOWNTO 0);
  TYPE vector_of_unsigned29 IS ARRAY (NATURAL RANGE <>) OF unsigned(28 DOWNTO 0);
  TYPE vector_of_signed29 IS ARRAY (NATURAL RANGE <>) OF signed(28 DOWNTO 0);
  TYPE vector_of_signed31 IS ARRAY (NATURAL RANGE <>) OF signed(30 DOWNTO 0);
  TYPE matrix_of_unsigned28 IS ARRAY (NATURAL RANGE <>, NATURAL RANGE <>) OF unsigned(27 DOWNTO 0);
  TYPE vector_of_unsigned4 IS ARRAY (NATURAL RANGE <>) OF unsigned(3 DOWNTO 0);
END combining_pac;

